#pragma once

enum LOADINGID { LOADING_STAGE, LOADING_BOSS, LOADING_END };
enum WINMODE { MODE_FULL, MODE_WIN };

enum OBJ_TYPE{ OBJ_PLAYER , OBJ_MONSTER, OBJ_UI, OBJ_NONE,  OBJ_END};


namespace Engine
{
	// ID_DYNAMIC : 매 프레임마다 갱신을 해야하는 컴포넌트 집단
	enum COMPONENTID{ID_DYNAMIC, ID_STATIC, ID_END };

	enum INFO {INFO_RIGHT, INFO_UP, INFO_LOOK, INFO_POS, INFO_END };
	enum ROTATION { ROT_X, ROT_Y, ROT_Z, ROT_END };
	enum TEXTYPE { TEX_NORMAL, TEX_CUBE, TEX_END };
	enum RENDERID { RENDER_PRIORITY, RENDER_ALPHA, RENDER_NONALPHA, RENDER_UI, RENDER_END };

	enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };
	enum MOUSEMOVESTATE { DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };

	enum MONSTER_STATE { MONSTER_IDLE, MONSTER_MOVE, MONSTER_ATTACK, MONSTER_DEAD, MONSTER_END };
	enum MONSTER_HEAD { HEAD_FRONT, HEAD_BACK, HEAD_END };
	enum MONSTER_NAME { NAME_SLIME, NAME_SOUL, NAME_MUTATION, SOUL_BULLET, NAME_END };

	enum BULLET_STATE { BULLET_IDLE, BULLET_MOVE, BULLET_END };

	enum UI_CATEGORY { UI_NONE, UI_MENU, UI_FRONT, UI_END };

}
